# Generated by Django 2.2.2 on 2020-02-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_repository_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='author',
            new_name='user',
        ),
    ]
