# Generated by Django 2.2.2 on 2020-02-24 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20200220_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('url', 'user')},
        ),
    ]
