# Generated by Django 2.2.2 on 2020-02-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200224_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
