# Generated by Django 2.2.2 on 2020-02-27 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200224_2143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user',)},
        ),
    ]
