# Generated by Django 2.2.2 on 2020-02-27 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20200227_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('url', 'user')},
        ),
    ]
